source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.3'

def import_pods
    pod 'GoogleMaps'
    pod 'GooglePlaces'
    pod 'MMDrawerController', '~> 0.5.7'
    pod 'iCarousel'
end

target 'Travel Notes' do
    xcodeproj 'Travel Notes.xcodeproj'
    import_pods
end